"""empty message

Revision ID: 012c909337a4
Revises: b73a660281a0
Create Date: 2023-03-09 17:34:14.400174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012c909337a4'
down_revision = 'b73a660281a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check', sa.Integer(), default=0))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('check')

    # ### end Alembic commands ###
