"""empty message

Revision ID: 1caed6108a02
Revises: 012c909337a4
Create Date: 2023-03-09 18:08:57.340472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caed6108a02'
down_revision = '012c909337a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.drop_column('check')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('views')

    # ### end Alembic commands ###
